### ISSUE TITLE
Something breaks with loading non-ALEX traces to prediction

### ISSUE THREAD

**Issue by eembees** [komodovaran/DeepFRET-GUI#49]
As Nikos mentioned there is an issue with loading non-ALEX traces. 
IDK how or what or which traces, but there is an issue in the prediction that causes more traces to be classified as scrambled.
@komodovaran feature or bug?

**Comment by komodovaran** [comment]
Is this a bug or a shortcoming of the model itself? Does the underlying prediction match the GUI?

**Comment by eembees** [comment]
Email from Hatice, the Ph.D. student of the editor of ELife:
 I started using the modules, the interface is quite nice and user friendly. 

I have a basic question that would help a lot with my data. In the documentation it says that extracted intensity-time trajectories can directly be loaded to the software in txt format. So my usage starts with traces module.

I believe Traces module uses 5 data types when analyzing traces. Donor emission, Acceptor emission from FRET, Acceptor emission from DIRECTexc., stoichiometry and FRET efficiency. In my data I lack the 3rd and 4th types of data because I am not doing ALEX, but it seems like that greatly influences the way traces are classified. I tried simulating traces using DEEPFret’s trace generator and when I replace the Acceptor emission from DIRECTexc. and stoichiometry columns  with either nothing or zeros, the trace gets classified as scrambled or aggregate while with that data in it, it is classified as 1 -state. I believe one of the reasons  this happens is because somehow the software does not seem to pick up the correct photobleaching time. 

Is there a simple solution to fix this? How can I substitute those columns in a way that would not affect the final classification or photobleaching time detection?

Thanks a lot for all your help

**Comment by eembees** [comment]
> Is this a bug or a shortcoming of the model itself? Does the underlying prediction match the GUI?

I wonder if this is because it doesn't detect the non-ALEX trace and ends up using the ALEX-trained model?

**Comment by eembees** [comment]
@komodovaran you found a solution wrt column names? 
Make a quick PR / commit to README to specify expected behavior?

**Comment by komodovaran** [comment]
The issue is column order and specification.

At the very least, it must have `D-Dexc-rw` and `A-Dexc-rw`. The first column must be `D-Dexc-rw` or `D-Dexc-bg`, because DeepFRET skips past custom headers to look for the columns. Will update readme.
